FROM node:16.14-alpine

ENV PATH /back/node_modules/.bin:$PATH

WORKDIR /back

# RUN apk add --update python
RUN apk add --no-cache python3 g++ make

COPY package*.json yarn.lock ./

RUN yarn install

COPY . .

# linux 서버에 저장된 env 파일(mongoDB Atlas 개인디비 주소, 카카오 redirectURL 등 저장) 복사!
# COPY /home/elice/env $HOME/node_docker/

ENTRYPOINT ["yarn", "start"]