FROM node:16.14-alpine as builder

ENV PATH /front/node_modules/.bin:$PATH

WORKDIR /front

# RUN apk add --update python

COPY package*.json yarn.lock ./

RUN yarn install --silent --progress=false

# 소스를 작업폴더로 복사하고 빌드
COPY . .

# RUN yarn build --silent --progress=false

# linux 서버에 저장된 env 파일(mongoDB Atlas 개인디비 주소, 카카오 redirectURL 등 저장) 복사!
# COPY /home/elice/env $HOME/node_docker/
